version: "3.8"
services:

  frontend:
    image: 192479299400.dkr.ecr.ap-southeast-1.amazonaws.com/sit-careers:fe-dev
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile.dev
    working_dir: /app
    container_name: sit-careers-fe
    env_file: .env
    ports:
      - "3000:3000"
    networks:
      - sit-careers

  fe-nginx:
    image: 192479299400.dkr.ecr.ap-southeast-1.amazonaws.com/sit-careers:fe-nginx-dev
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile.dev
    working_dir: /etc/nginx
    container_name: sit-careers-fe-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/dev-sit-cc.conf:/etc/nginx/conf.d/default.conf
    networks:
      - sit-careers

networks:
  sit-careers:
    driver: bridge
  sit-careers-api_sit-careers:
    external: true
